# Generated by Django 4.1.2 on 2022-10-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=30)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Mail', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
