# Generated by Django 4.1.2 on 2022-10-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_user_name_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Mail',
            new_name='eMail',
        ),
    ]
