# Generated by Django 4.1.2 on 2022-10-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_mail_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eMail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Phone_Number',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_Name',
            new_name='username',
        ),
    ]
