# Generated by Django 4.1.2 on 2022-11-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='pic',
            field=models.FileField(default='sad.jpg', upload_to='profile'),
        ),
    ]
