# Generated by Django 4.1.2 on 2022-11-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_blog_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point', models.CharField(max_length=50)),
                ('pickout_point', models.CharField(max_length=50)),
                ('car_name', models.CharField(max_length=50)),
                ('allowed_participants', models.IntegerField()),
                ('arrival_time', models.CharField(max_length=50)),
                ('drop_time', models.CharField(max_length=50)),
            ],
        ),
    ]
