# Generated by Django 4.1.2 on 2022-11-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_myride'),
    ]

    operations = [
        migrations.AddField(
            model_name='myride',
            name='phone_number',
            field=models.CharField(default=True, max_length=12),
        ),
    ]
