# Generated by Django 4.1.2 on 2022-11-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_myride_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myride',
            name='phone_number',
            field=models.CharField(default='', max_length=12),
        ),
    ]
