# Generated by Django 4.1.2 on 2022-11-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_myride_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myride',
            name='car_name',
        ),
    ]
