# Generated by Django 4.1.2 on 2022-11-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_myride_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myride',
            name='price',
            field=models.IntegerField(),
        ),
    ]
