# Generated by Django 4.1.2 on 2022-11-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_myride_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='myride',
            name='date',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
