# Generated by Django 4.1.2 on 2022-11-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_myride_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myride',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.data'),
        ),
    ]
