# Generated by Django 4.1.2 on 2022-11-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_myride_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myride',
            name='user',
        ),
    ]
