# Generated by Django 4.1.2 on 2022-11-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myride',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
