# Generated by Django 4.1.2 on 2022-12-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_blog_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myride',
        ),
    ]
