# Generated by Django 4.1.2 on 2022-12-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_delete_myride'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('pickup_point', models.CharField(max_length=50)),
                ('pickout_point', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('price', models.IntegerField()),
                ('allowed_participants', models.IntegerField()),
                ('arrival_time', models.CharField(max_length=50)),
                ('drop_time', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.data')),
            ],
        ),
    ]
