# Generated by Django 4.1.2 on 2022-12-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_rideinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rideinfo',
        ),
    ]
