# Generated by Django 4.1.2 on 2022-12-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_rideinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rideinfo',
        ),
    ]
