# Generated by Django 4.1.2 on 2022-12-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_rideinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rideinfo',
        ),
    ]
