# Generated by Django 4.1.2 on 2022-12-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_delete_rideinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rideinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=12)),
                ('myride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.myride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.data')),
            ],
        ),
    ]
