# Generated by Django 4.1.2 on 2022-12-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_rideinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rideinfo',
        ),
    ]
