# Generated by Django 4.1.2 on 2022-12-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_rideinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rideinfo',
        ),
    ]
