# Generated by Django 4.1.2 on 2022-12-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_rideinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pic',
            field=models.FileField(default='sad.png', upload_to='blogs'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pic',
            field=models.FileField(default='sad.png', upload_to='profile'),
        ),
    ]
